ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 2
warningCode = 1

[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.exported]
[rule.if-return]
[rule.increment-decrement]
[rule.var-naming]
[rule.var-declaration]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
# [rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.argument-limit]
    arguments = [6]
[rule.cyclomatic]
    arguments = [10]
# [rule.file-header]
[rule.empty-block]
[rule.superfluous-else]
# [rule.confusing-naming]
# [rule.get-return]
[rule.modifies-parameter]
[rule.confusing-results]
# [rule.deep-exit]
[rule.unused-parameter]
[rule.unreachable-code]
# [rule.add-constant]
